# Generated by Django 3.2 on 2025-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ruta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "origen",
                    models.CharField(
                        choices=[("Santiago", "Santiago"), ("Valparaiso", "Valparaiso"), ("Concepcion", "Concepcion")],
                        max_length=50,
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        choices=[("Santiago", "Santiago"), ("Valparaiso", "Valparaiso"), ("Concepcion", "Concepcion")],
                        max_length=50,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_salida", models.TimeField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
