# Generated by Django 3.2 on 2025-10-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='coordenadas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
