# Generated by Django 3.2 on 2025-10-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_ruta_coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
